CUDA_VISIBLE_DEVICES=0 python train_arithmetic.py \
  --peft_method=moe_lora \
  --moe_expert_ranks=8,16,32 \
  --moe_top_k=1 \
  --moe_router_hidden_dim=0 \
  --moe_expert_chunk_size=64 \
  --moe_gradient_checkpoint_experts \
  --lr=1e-3 \
  --hf_fast_download \
  --hf_preload \
  --hf_prefer_safetensors
