CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0} python train_cr.py \
  --adapter_type evolve_lora \
  --hf_fast_download --hf_preload --hf_prefer_safetensors "$@" \
  --model "meta-llama/Llama-3.2-1B" \
  --evolve_rank_delay_ratio 0.18 \
  --evolve_r_min 2 \
  --evolve_beta 0.001 \
  --evolve_alpha_max 0.002 \
  --evolve_anneal_k 8.5e-6 \
  --evolve_gate_floor 0.12 \
  --evolve_complexity_ema 0.9 \
  --lora_r 32 \
  --lora_alpha 32 \
  --lora_dropout 0.04 \
  --batch_size 6 \
  --grad_acc_steps 24 \
  --epochs 2 \
  --scheduler linear \
  --warmup_ratio 0.1 \
  --max_seq_length 256 \
  --lr 4.05e-4
